Expected SQL item bug fix with order by computed column
graphile/graphile-engine pull request #741
Opened 2021-05-14 14:15 UTC by pszafer

## Description

Issue: https://github.com/graphile/graphile-engine/issues/740
## Performance impact

## Security impact

## Checklist

- [x] My code matches the project's code style and `yarn lint:fix` passes.
Passes with multiple warning from different files.
- [ ] I've added tests for the new feature, and `yarn test` passes.
- [ ] I have detailed the new feature in the relevant documentation.
- [ ] I have added this feature to 'Pending' in the `RELEASE_NOTES.md` file (if one exists).
- [ ] If this is a breaking change I've explained why.

2021-05-17 09:32 UTC, benjie requested changes

2021-05-17 09:32 UTC, benjie commented on packages/postgraphile-core/__tests__/fixtures/mutations/mutation-delete.graphql
> +    node {
when requesting an edge we should also request the cursor (otherwise what’s the point?)

```suggestion
    cursor
    node {
```

2021-05-24 10:01 UTC, benjie commented
@pszafer You've added `cursor` but I think you need to update the snapshots (`yarn test -u`) to update the snapshots?

2021-05-26 13:47 UTC, benjie approved these changes

2021-05-26 13:57 UTC, merged

2021-05-26 13:57 UTC, pszafer commented
sorry I missed your message. I see it's merged already. Thanks!